"""科研制图代码生成工具 — 生成出版级 matplotlib 代码

根据数据描述和图表类型，生成可直接运行的 Python 脚本。
自动应用 figure-styles.mplstyle 样式，符合 ApJ/MNRAS 标准。

用法:
  generate_figure_code(data_description="...", plot_type="spectrum", style="apj")
    → 返回完整 Python 脚本源码
"""
import os
from typing import Optional

from astro_nova.providers.base import LLMMessage
from astro_nova.providers.manager import manager as provider_manager
from astro_nova.tools.registry import Tool, registry
from astro_nova.utils.logger import logger

# matplotlib 样式文件路径
MPLSTYLE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "references", "figure-styles.mplstyle"
)

CODE_OUTPUT_DIR = os.path.join(os.path.expanduser("~"), ".astro-nova", "figures")

PLOT_TYPE_PROMPTS = {
    "spectrum": "光谱图: x轴=波长/频率, y轴=流量/强度, 展示谱线特征",
    "lightcurve": "光变曲线: x轴=时间(MJD/秒), y轴=流量/星等, 展示时域变化",
    "sed": "SED (能谱分布): x轴=频率/波长(log), y轴=流量密度(log), 多波段数据点+拟合曲线",
    "contour": "等高线/置信区间图: 展示参数空间的后验分布",
    "histogram": "直方图: 统计分布",
    "scatter": "散点图: 两个变量的相关关系",
    "multi_panel": "多面板组合图: 2×2 或 3×2 子图布局",
}


async def generate_figure_code(
    data_description: str,
    plot_type: str = "spectrum",
    style: str = "apj",
    additional_requirements: str = "",
) -> dict:
    """根据数据描述生成出版级 matplotlib 代码

    Args:
        data_description: 数据描述，说明数据格式、列名、物理量
        plot_type: 图表类型 (spectrum / lightcurve / sed / contour / histogram / scatter / multi_panel)
        style: 期刊风格 (apj / mnras / aa)
        additional_requirements: 额外要求

    Returns:
        {"code": "完整 Python 脚本", "file_path": "保存路径", "plot_type": "..."}
    """
    os.makedirs(CODE_OUTPUT_DIR, exist_ok=True)

    plot_desc = PLOT_TYPE_PROMPTS.get(plot_type, plot_type)

    # 读取 mplstyle 内容作为参考
    style_content = ""
    try:
        with open(MPLSTYLE_PATH, "r", encoding="utf-8") as f:
            style_content = f.read()
    except FileNotFoundError:
        style_content = "# figure-styles.mplstyle 未找到"

    provider = provider_manager.get_provider("code") or provider_manager.get_provider("chat")
    if not provider:
        return {"error": "没有可用的 LLM Provider", "code": ""}

    style_notes = {
        "apj": "刻度向内，黑白打印友好，Times New Roman 字体",
        "mnras": "刻度向外，单栏 3.25in 双栏 6.75in",
        "aa": "刻度向外，单栏 8cm 双栏 16cm",
    }.get(style, "ApJ 标准")

    messages = [
        LLMMessage(role="system", content=f"""你是一个天文学科研制图专家。生成完整可运行的 Python/matplotlib 代码。

制图规范:
- 应用样式: plt.style.use("{MPLSTYLE_PATH}")
- {style_notes}
- 输出 PDF 矢量图
- 代码必须包含完整的 import、数据处理、绘图、保存
- 数据用注释中的示例数据或从文件读取 (生成文件读取代码)
- x/y 轴标签包含单位和物理量名称
- 色盲友好色板 (IBM colorblind-safe / viridis)
- 图例放在合适位置
- 如果用户没提供真实数据，用注释占位说明数据格式

代码结构:
```python
#!/usr/bin/env python3
\"\"\"[图表标题] — 由 astro-nova 生成\"\"\"
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams

# 应用样式
plt.style.use("{MPLSTYLE_PATH}")

# [数据加载或示例数据]
# ...

# [绘图代码]
# ...

# 保存
plt.savefig("output.pdf", bbox_inches="tight")
print("[OK] 已保存 output.pdf")
```"""),
        LLMMessage(role="user", content=f"""图表类型: {plot_type} ({plot_desc})
期刊风格: {style}
数据描述: {data_description}
额外要求: {additional_requirements}

请生成完整可运行的 Python 绘图代码。"""),
    ]

    try:
        resp = await provider.chat(messages)
        code = resp.content

        # 提取代码块
        import re
        match = re.search(r"```python\n(.*?)```", code, re.DOTALL)
        if match:
            code = match.group(1).strip()

        # 保存文件
        fname = f"figure_{plot_type}.py"
        file_path = os.path.join(CODE_OUTPUT_DIR, fname)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(f'"""Generated by astro-nova figure_generator ({plot_type})"""\n')
            f.write(code)

        logger.info(f"制图代码已保存: {file_path}")
        return {
            "code": code,
            "file_path": file_path,
            "plot_type": plot_type,
            "message": f"代码已生成，运行: python {file_path}",
        }
    except Exception as e:
        logger.error(f"制图代码生成失败: {e}")
        return {"error": str(e), "code": ""}


def register_tools():
    registry.register(Tool(
        name="generate_figure_code",
        description="根据数据描述和图表类型生成出版级 matplotlib 绘图代码（PDF 矢量图），支持光谱图/光变曲线/SED/等高线/散点图/多面板组合图",
        parameters={
            "type": "object",
            "properties": {
                "data_description": {
                    "type": "string",
                    "description": "数据描述：数据格式、列名、物理量、数值范围",
                },
                "plot_type": {
                    "type": "string",
                    "enum": ["spectrum", "lightcurve", "sed", "contour", "histogram", "scatter", "multi_panel"],
                    "description": "图表类型",
                },
                "style": {
                    "type": "string",
                    "enum": ["apj", "mnras", "aa"],
                    "description": "期刊风格",
                },
                "additional_requirements": {
                    "type": "string",
                    "description": "额外要求，如色板、图例位置、标注等",
                },
            },
            "required": ["data_description", "plot_type"],
        },
        handler=generate_figure_code,
    ))
