"""论文写作辅助工具 — 按 ApJ/MNRAS/A&A 标准格式撰写论文各章节

用法:
  write_paper_section(section_type="introduction", journal="apj", context="...")
    → 返回 .tex 格式的章节内容
  write_full_paper(outline={...}, journal="apj")
    → 生成完整论文骨架
"""
import os
from typing import Optional

from astro_nova.providers.base import LLMMessage
from astro_nova.providers.manager import manager as provider_manager
from astro_nova.tools.registry import Tool, registry
from astro_nova.utils.logger import logger

from astro_nova.utils.paths import get_data_dir as _get_data_dir

PAPER_DIR = _get_data_dir("writing")

JOURNAL_INFO = {
    "apj": {
        "name": "ApJ / AJ / ApJL",
        "doc_class": "aastex701",
        "citation": "author-year (\\citep, \\citet)",
        "abstract_limit": 250,
    },
    "mnras": {
        "name": "MNRAS",
        "doc_class": "mnras",
        "citation": "author-year (\\citep, \\citet)",
        "abstract_limit": 300,
    },
    "aa": {
        "name": "A&A",
        "doc_class": "aa",
        "citation": "author-year (\\citep, \\citet)",
        "abstract_limit": 300,
    },
}

SECTION_PROMPTS = {
    "abstract": "撰写论文摘要：背景1句 → 问题1句 → 方法1-2句 → 结果2-3句 → 结论1句",
    "introduction": "撰写引言：研究领域背景 → 已有工作的不足(gap) → 本文目标与创新 → 论文结构预览",
    "methods": "撰写方法章节：观测/实验/理论方法描述，需包含足够的细节使结果可复现",
    "results": "撰写结果章节：核心发现，定量呈现，引用图表 (Figure \\ref{{fig:...}}, Table \\ref{{tab:...}})",
    "discussion": "撰写讨论章节：结果解释 → 与前人工作对比 → 局限性 → 未来展望",
    "conclusion": "撰写结论：总结核心发现1-2句 → 科学意义 → 未来工作",
}


async def write_paper_section(
    section_type: str,
    journal: str = "apj",
    title: str = "",
    context: str = "",
    additional_notes: str = "",
) -> dict:
    """按期刊格式撰写论文章节

    Args:
        section_type: 章节类型 (abstract / introduction / methods / results / discussion / conclusion)
        journal: 期刊 (apj / mnras / aa)
        title: 论文标题
        context: 上下文内容（已有结果、数据描述、相关文献等）
        additional_notes: 额外要求

    Returns:
        {"section": "...", "tex": "...", "word_count": N}
    """
    os.makedirs(PAPER_DIR, exist_ok=True)

    journal_cfg = JOURNAL_INFO.get(journal, JOURNAL_INFO["apj"])
    section_prompt = SECTION_PROMPTS.get(section_type, f"撰写{section_type}章节")

    provider = provider_manager.get_provider("write") or provider_manager.get_provider("chat")
    if not provider:
        return {"error": "没有可用的 LLM Provider", "section": ""}

    messages = [
        LLMMessage(role="system", content=f"""你是一个天文学论文写作专家。
期刊: {journal_cfg['name']}
文档类: {journal_cfg['doc_class']}
引用格式: {journal_cfg['citation']}
摘要字数限制: {journal_cfg['abstract_limit']} 字

写作要求:
- 使用学术英语 (UK/US 拼写按期刊要求)
- 准确引用文献 (\\citet/\\citep)
- {section_prompt}
- 输出 LaTeX 格式 (包含 \\section/\\subsection/\\label/\\ref/\\citep 等)
- 不需要包含 \\documentclass 等导言区，只输出章节内容
- 如果引用了文献，使用 \\citet{{Author2023}} 或 \\citep{{Author2023}} 格式占位"""),
        LLMMessage(role="user", content=f"""论文标题: {title}
章节: {section_type}
上下文: {context}
额外要求: {additional_notes}

请撰写该章节的 LaTeX 内容。"""),
    ]

    try:
        resp = await provider.chat(messages)
        section = resp.content
        import re

        # 提取代码块
        match = re.search(r"```(?:latex|tex)?\n(.*?)```", section, re.DOTALL)
        if match:
            section = match.group(1).strip()

        word_count = len(re.findall(r"\b[a-zA-Z]+\b", section))

        # 保存
        fname = f"{section_type}.tex"
        file_path = os.path.join(PAPER_DIR, fname)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(f"% {journal_cfg['name']} — {section_type}\n")
            f.write(f"% Generated by astro-nova writing_assistant\n\n")
            f.write(section)

        return {"section": section, "tex": file_path, "word_count": word_count}
    except Exception as e:
        logger.error(f"写作失败: {e}")
        return {"error": str(e), "section": ""}


def register_tools():
    registry.register(Tool(
        name="write_paper_section",
        description="按 ApJ/MNRAS/A&A 标准格式撰写论文的一个章节（摘要/引言/方法/结果/讨论/结论），输出 LaTeX",
        parameters={
            "type": "object",
            "properties": {
                "section_type": {
                    "type": "string",
                    "enum": ["abstract", "introduction", "methods", "results", "discussion", "conclusion"],
                    "description": "论文章节类型",
                },
                "journal": {
                    "type": "string",
                    "enum": ["apj", "mnras", "aa"],
                    "description": "目标期刊",
                },
                "title": {"type": "string", "description": "论文标题"},
                "context": {
                    "type": "string",
                    "description": "写作上下文：已有结果、数据描述、相关文献、关键数值等",
                },
                "additional_notes": {"type": "string", "description": "额外要求"},
            },
            "required": ["section_type", "context"],
        },
        handler=write_paper_section,
    ))
